theme: jekyll-theme-slate
show_downloads: true
layout: default
github:
  zip1_url: https://MaggieZhang17.github.io/OptoEd/ph-pages/GUI3.zip
  zip2_url: https://MaggieZhang17.github.io/OptoEd/ph-pages/GUI3.zip
